
INSERT INTO currency(currency_code) Values('EUR');
INSERT INTO currency(currency_code) Values('USD');

INSERT INTO currency(currency_code) Values('AUD');
INSERT INTO currency(currency_code) Values('ATS');
INSERT INTO currency(currency_code) Values('BEF');
INSERT INTO currency(currency_code) Values('CZK');
INSERT INTO currency(currency_code) Values('DKK');
INSERT INTO currency(currency_code) Values('EEK');
INSERT INTO currency(currency_code) Values('FIM');
INSERT INTO currency(currency_code) Values('FRF');
INSERT INTO currency(currency_code) Values('GRD');
INSERT INTO currency(currency_code) Values('ESP');
INSERT INTO currency(currency_code) Values('NLG');
INSERT INTO currency(currency_code) Values('IEP');
INSERT INTO currency(currency_code) Values('JPY');
INSERT INTO currency(currency_code) Values('CAD');
INSERT INTO currency(currency_code) Values('LUF');
INSERT INTO currency(currency_code) Values('NOK');
INSERT INTO currency(currency_code) Values('PTE');
INSERT INTO currency(currency_code) Values('CHF');
INSERT INTO currency(currency_code) Values('SEK');
INSERT INTO currency(currency_code) Values('HUF');
INSERT INTO currency(currency_code) Values('GBP');
INSERT INTO currency(currency_code) Values('ITL');
INSERT INTO currency(currency_code) Values('XDR');

INSERT INTO currency(currency_code) Values('THB');
INSERT INTO currency(currency_code) Values('HKD');  
INSERT INTO currency(currency_code) Values('NZD');
INSERT INTO currency(currency_code) Values('SGD');
INSERT INTO currency(currency_code) Values('UAH'); 
INSERT INTO currency(currency_code) Values('ISK');
INSERT INTO currency(currency_code) Values('HRK');
INSERT INTO currency(currency_code) Values('RON'); 
INSERT INTO currency(currency_code) Values('BGN');
INSERT INTO currency(currency_code) Values('TRY');
INSERT INTO currency(currency_code) Values('ILS'); 
INSERT INTO currency(currency_code) Values('CLP'); 
INSERT INTO currency(currency_code) Values('PHP'); 
INSERT INTO currency(currency_code) Values('MXN');
INSERT INTO currency(currency_code) Values('ZAR');
INSERT INTO currency(currency_code) Values('BRL');
INSERT INTO currency(currency_code) Values('MYR'); 
INSERT INTO currency(currency_code) Values('RUB'); 
INSERT INTO currency(currency_code) Values('IDR'); 
INSERT INTO currency(currency_code) Values('INR'); 
INSERT INTO currency(currency_code) Values('KRW');
INSERT INTO currency(currency_code) Values('CNY');
INSERT INTO currency(currency_code) Values('LVL');
INSERT INTO currency(currency_code) Values('CYP'); 
INSERT INTO currency(currency_code) Values('SKK');
INSERT INTO currency(currency_code) Values('MTL'); 
INSERT INTO currency(currency_code) Values('LTL'); 
INSERT INTO currency(currency_code) Values('SIT');

INSERT INTO country(country_name) Values('Niemcy');
INSERT INTO country(country_name) Values('Stany Zjednoczone');
INSERT INTO Rate(value,date,currency_id) Values('4.4753','2012-01-04',1);

